# What this notebook is for?

This notebook aids the process of evaluating accuracy measures and predicting class outputs of already trained models.

In [2]:
import tensorflow as tf
import numpy as np
import h5py as h5

## Reading data

Throughout this project we've used these functions in order to read the processed data.

In [3]:
def make_dimensions_compatible(arr):
    
    return arr.reshape(arr.shape[0],-1,1)

In [4]:
def load_dataset(dataset_iter=1, window_size=512):
    global X_train, Y_train, X_dev, Y_dev, X_test, Y_test
    
    dataset_relative_path = 'dataset/random-iter-%d/' % dataset_iter
    
    datafile = dataset_relative_path + 'datafile%d.h5' % window_size

    with h5.File(datafile, 'r') as datafile:
        X_train = np.array(datafile['X_train'])
        Y_train = np.array(datafile['Y_train'])

        X_dev = np.array(datafile['X_dev'])
        Y_dev = np.array(datafile['Y_dev'])

        X_test = np.array(datafile['X_test'])
        Y_test = np.array(datafile['Y_test'])
        
        # setting the rank of the data to be compatible with 1d convolution functions
        # defined in tensorflow
        X_train = make_dimensions_compatible(X_train)
        X_dev = make_dimensions_compatible(X_dev)
        X_test = make_dimensions_compatible(X_test)
        
        # normalization
        X_train = X_train / 1000
        X_dev = X_dev / 1000
        X_test = X_test / 1000

In [5]:
def get_session_path(dataset_iter=1, window_size=512, model_num=1, model_prefix='cnn', model_suffix='_lr-0.00002_mbs-128'):
    return ('train/dataset-%d-%d/' + model_prefix + '%d' + model_suffix + '/') % (window_size, dataset_iter, model_num)



## Prediction

In [6]:
def predict(X_test, session_path, model_file, Y_test_onehot=None):

    tf.reset_default_graph()

    checkpoint_path = session_path
    model_path = session_path + model_file

    with tf.Session() as sess:
        loader = tf.train.import_meta_graph(model_path)
        loader.restore(sess, tf.train.latest_checkpoint(checkpoint_path))

        graph = tf.get_default_graph()

        X = graph.get_tensor_by_name('X:0')
        Y = graph.get_tensor_by_name('Y:0')
        is_train = graph.get_tensor_by_name('is_train:0')
        
#         epoch_counter = graph.get_tensor_by_name('epoch_counter:0')
#         print(epoch_counter.eval())

        Y_hat = graph.get_tensor_by_name('softmax_output:0')

        predict_op = tf.argmax(Y_hat, 1)

        y_hat_test = predict_op.eval({X: X_test, is_train: False})
        
        # print the accuracy of the test set if the labels are provided
        if (Y_test_onehot is not None):
            y_test = np.argmax(Y_test_onehot, 1)
            acc = (y_hat_test == y_test).mean()
        

    return y_hat_test, acc


## Prediction with majority voting on ensemble network

In [7]:
def predict_voting(X_test_voting, session_path, model_file):

    tf.reset_default_graph()

    checkpoint_path = session_path
    model_path = session_path + model_file
    
    y_hat_test_voting = []

    with tf.Session() as sess:
        loader = tf.train.import_meta_graph(model_path)
        loader.restore(sess, tf.train.latest_checkpoint(checkpoint_path))

        graph = tf.get_default_graph()

        X = graph.get_tensor_by_name('X:0')
        is_train = graph.get_tensor_by_name('is_train:0')

        Y_hat = graph.get_tensor_by_name('softmax_output:0')

        predict_op = tf.argmax(Y_hat, 1)
        
        classname, idx, counts = tf.unique_with_counts(predict_op)
        predict_voting_op = tf.gather(classname, tf.argmax(counts))

        # no. of training examples with the original feature size
        m = X_test_voting.shape[0]
        
        # no. of split training examples of each original example
        m_each = X_test_voting.shape[1]
        
        for ex in range(m):
            x_test_voting = make_dimensions_compatible(X_test_voting[ex])
            pred = predict_voting_op.eval({X: x_test_voting, is_train: False})
            
            y_hat_test_voting.append(pred)

    return y_hat_test_voting

### Accuracy measure

In [40]:
model_num = 8
window_size = 1024
dataset_iters = (1, 2, 3, 4, 5, 6, 7, 8)

accuracies = np.array([])

for dataset_iter in dataset_iters:
    load_dataset(dataset_iter=dataset_iter, window_size=window_size)
    predictions, acc = predict(X_test, get_session_path(dataset_iter=dataset_iter, window_size=window_size, model_num=model_num), 'model.meta', Y_test_onehot=Y_test)
    accuracies = np.append(accuracies, acc)

accuracies = accuracies * 100
print(accuracies)

print("Mean accuracy: %f" % accuracies.mean())

INFO:tensorflow:Restoring parameters from train/dataset-1024-1/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-2/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-3/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-4/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-5/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-6/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-7/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-8/cnn8_lr-0.00002_mbs-128/model
[99.42857143 98.85714286 98.28571429 97.14285714 96.         94.85714286
 99.42857143 94.85714286]
Mean accuracy: 97.357143


### Single model accuracy with voting measure

In [41]:
model_num = 8
window_size = 1024
dataset_iters = (1, 2, 3, 4, 5, 6, 7, 8)

accuracies_voting = np.array([])
sensitivities_voting = np.array([])
specificities_voting = np.array([])
precisions_voting = np.array([])

for dataset_iter in dataset_iters:
    dataset_relative_path = 'dataset/random-iter-%d/' % dataset_iter
    testfile = (dataset_relative_path + 'testset_voting_%d.h5') % window_size
    session_path = get_session_path(dataset_iter=dataset_iter, window_size=window_size, model_num=model_num)
    model_file = 'model.meta'

    with h5.File(testfile, 'r') as testfile:
        X_test_voting = testfile['X']
        X_test_voting = np.array(X_test_voting) / 1000
        y_test_voting = np.array(testfile['Y'])
        
        no_of_classes = 3

        y_hat_test_voting = np.array(predict_voting(X_test_voting, session_path, model_file))

        acc_voting_model = (y_test_voting == y_hat_test_voting).mean()
        accuracies_voting = np.append(accuracies_voting, acc_voting_model)
        
        # specificity and sensitivity
        specificity = 0
        sensitivity = 0
        precision = 0
        for i in range(no_of_classes):
            specificity_vector = ((y_hat_test_voting != i) == (y_test_voting != i))[y_test_voting != i]
            sensitivity_vector = ((y_hat_test_voting == i) == (y_test_voting == i))[y_test_voting == i]
            precision_vector = ((y_hat_test_voting == i) == (y_test_voting == i))[y_hat_test_voting == i]
            
            specificity = specificity + specificity_vector.sum() / len(specificity_vector)
            sensitivity = sensitivity + sensitivity_vector.sum() / len(sensitivity_vector)
            precision = precision + precision_vector.sum() / len(precision_vector)
        
        specificity = specificity / no_of_classes
        sensitivity = sensitivity / no_of_classes
        precision = precision / no_of_classes
        
        specificities_voting = np.append(specificities_voting, specificity)
        sensitivities_voting = np.append(sensitivities_voting, sensitivity)
        precisions_voting = np.append(precisions_voting, precision)


# Computing F-Score
Pre = precisions_voting.mean()
Sen = sensitivities_voting.mean()
F_Score = (2 * Pre * Sen) / (Pre + Sen)
        
accuracies_voting = accuracies_voting * 100
print("Accuracy with voting: ", accuracies_voting)
print("Mean accuracy with voting: %f" % accuracies_voting.mean())
print("\n\n")
print("Specifities: ", specificities_voting)
print("Mean specificity with voting: %f" % specificities_voting.mean())
print("\n\n")
print("Sensitivities: ", sensitivities_voting)
print("Mean sensitivity with voting: %f" % sensitivities_voting.mean())
# print("Mean precision with voting: %f" % Pre)
print("Mean F-Score with voting: %f" % F_Score)
print("Standard deviation: %f" % accuracies_voting.std())

# print("Actual labels:\n", y_test_voting)
# print("\n\nPredictions:\n", y_hat_test_voting)


INFO:tensorflow:Restoring parameters from train/dataset-1024-1/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-2/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-3/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-4/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-5/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-6/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-7/cnn8_lr-0.00002_mbs-128/model
INFO:tensorflow:Restoring parameters from train/dataset-1024-8/cnn8_lr-0.00002_mbs-128/model
Accuracy with voting:  [100. 100.  98.  98.  96.  98. 100.  96.]
Mean accuracy with voting: 98.250000



Specifities:  [1.         1.         0.98888889 0.98888889 0.97777778 0.98888889
 1.         0.97777778]
Mean specificity with voting: 0.990278



Sens

In [43]:
a = np.array([0., 0., 1., 1., 1, 0., 2., 2., 0])
b = np.array([0, 0, 0, 1, 0, 0, 1, 2, 1])

In [44]:
((b != 0) == (a != 0))[a != 0]

array([False,  True, False,  True,  True])

In [45]:
((b == 1) == (a ==1))[a == 1]

array([False,  True, False])

In [31]:
(((b != 0) == (a != 0))[a != 0]).sum()

3

In [51]:
((b == 1) == (a ==1))[b == 1]

array([ True, False, False])