In [1]:
import tensorflow as tf
import numpy as np
from tensorflow.python.framework import ops

In [105]:
np.random.seed(5)

X_train = np.random.randint(1,10, size=(2,20,1)).astype(np.float32)
Y_train = np.array([[1,0,0],[0,0,1]]).astype(np.float32)

In [106]:
print(X_train)
print('\n\n')
print(Y_train)

[[[4.]
  [7.]
  [7.]
  [1.]
  [9.]
  [5.]
  [8.]
  [1.]
  [1.]
  [8.]
  [2.]
  [6.]
  [8.]
  [1.]
  [2.]
  [5.]
  [7.]
  [3.]
  [2.]
  [3.]]

 [[8.]
  [1.]
  [6.]
  [1.]
  [1.]
  [5.]
  [5.]
  [4.]
  [3.]
  [5.]
  [7.]
  [4.]
  [4.]
  [3.]
  [2.]
  [6.]
  [8.]
  [5.]
  [4.]
  [2.]]]



[[1. 0. 0.]
 [0. 0. 1.]]


In [107]:
def create_placeholders(n_x, n_y):
    """
    Creates Tensorflow placeholders that act for input data and their labels
    
    Arguments:
    n_x - no. of features for X
    n_x - no. of classes for Y
    
    Returns:
    X - placeholder for data that contains input featurs,
        shape: (no. of examples, no. of features). No. of examples is set to None
    Y - placeholder for data that contains output class labels,
        shape (no. of examples, no. of classes). No. of examples is set ot None
    """
    
    X = tf.placeholder(tf.float32, name='X', shape=(None, n_x, 1))
    Y = tf.placeholder(tf.float32, name='Y', shape=(None, n_y))
    
    return X,Y

In [118]:
np.random.seed(6)
c1w = np.random.randint(0,3,size=(5,1,3)).astype(np.float32)
print(c1w)

np.random.seed(7)
c2w = np.random.randint(-2,3,size=(4,3,1)).astype(np.float32)
print(c2w)

np.random.seed(8)
c3w = np.random.randint(-2,3,size=(2,1,2)).astype(np.float32)
print(c3w)

[[[2. 1. 0.]]

 [[2. 1. 2.]]

 [[0. 2. 1.]]

 [[1. 1. 1.]]

 [[2. 1. 0.]]]
[[[ 2.]
  [-1.]
  [ 1.]]

 [[ 1.]
  [ 2.]
  [-1.]]

 [[-2.]
  [-1.]
  [ 0.]]

 [[ 0.]
  [-2.]
  [ 2.]]]
[[[ 1.  2.]]

 [[-1. -1.]]]


In [180]:
def get_params():
    parameters = {}
    parameters['CONV1_W'] = tf.get_variable('CONV1_W', initializer=tf.constant(c1w))
    parameters['CONV1_Str'] = 3
    
    parameters['CONV2_W'] = tf.get_variable('CONV2_W', initializer=tf.constant(c2w))
    parameters['CONV2_Str'] = 2
    
    parameters['CONV3_W'] = tf.get_variable('CONV3_W', initializer=tf.constant(c3w))
    parameters['CONV3_Str'] = 2
    
    parameters['FC1_units'] = 2
    
    parameters['DO_prob'] = 0.5
    
    parameters['output_classes'] = 2
    
    return parameters

In [190]:
def forward_propagation(X, parameters, training=False):
    """
    Implements the forward propagation for the model:
    (CONV BN RELU) -> (CONV BN RELU) -> (CONV BN RELU) -> (FC RELU DROPOUT) -> FC
    
    Arguments:
    X -- input dataset placeholder, of shape (input size, number of examples)
    parameters -- python dictionary containing your parameters
                  "CONV1_W", "CONV2_W", "CONV3_W", "FC1_units", "DO_prob", "output_classes"
                  the shapes are given in initialize_parameters

    Returns:
    Z3 -- the output of the last LINEAR unit (without softmax)
    """
    
    # Retrieve the parameters from the dictionary "parameters" 
    CONV1_W = parameters['CONV1_W']
    CONV1_Str = parameters['CONV1_Str']
    CONV2_W = parameters['CONV2_W']
    CONV2_Str = parameters['CONV2_Str']
    CONV3_W = parameters['CONV3_W']
    CONV3_Str = parameters['CONV3_Str']
    FC1_units = parameters['FC1_units']
    DO_prob = parameters['DO_prob']
    output_classes = parameters["output_classes"]
    
    
    #Layer 1
    # CONV
    Z1 = tf.nn.conv1d(X, CONV1_W, stride=CONV1_Str, padding='VALID', data_format='NWC', name='conv1')
    # Batch Normalization
    B1 = tf.contrib.layers.batch_norm(Z1, is_training=training)
#     # RELU
#     A1 = tf.nn.relu(B1)
    
#     #Layer 2
#     # CONV
#     Z2 = tf.nn.conv1d(A1, CONV2_W, stride=CONV2_Str, padding='VALID', data_format='NWC', name='conv2')
#     # Batch Normalization
#     B2 = tf.contrib.layers.batch_norm(Z2, is_training=training)
#     # RELU
#     A2 = tf.nn.relu(Z2)
    
#     #Layer 3
#     # CONV
#     Z3 = tf.nn.conv1d(A2, CONV3_W, stride=CONV3_Str, padding='VALID', data_format='NWC', name='conv3')
#     # Batch Normalization
#     B3 = tf.contrib.layers.batch_norm(Z3, is_training=training)
#     # RELU
#     A3 = tf.nn.relu(Z3)
    
#     # Flatten activations for FC layer
#     A3_flat = tf.contrib.layers.flatten(A3)
    
#     # Layer 4
#     # FC
#     A4 = tf.contrib.layers.fully_connected(A3_flat, FC1_units, activation_fn=tf.nn.relu)
#     # Dropout
#     A4_dropped = tf.contrib.layers.dropout(A4, keep_prob=DO_prob, is_training=training)
    
#     # Layer 5
#     # FC
#     A5 = tf.contrib.layers.fully_connected(A4_dropped, output_classes, activation_fn=None)
    
    return B1

In [191]:
ops.reset_default_graph()

update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
parameters = get_params()

with tf.Session() as sess, tf.control_dependencies(update_ops):
    
    X, Y = create_placeholders(20, 3)
    f = forward_propagation(X, parameters, training=True)
    
    init = tf.global_variables_initializer()
    init_l = tf.local_variables_initializer()
    sess.run(init)
    sess.run(init_l)
    
    result, _ = sess.run([f, update_ops], feed_dict={X: X_train, Y: Y_train})
    
    print(result)

[[[ 1.3994527   2.0976143   0.7139616 ]
  [-0.26476097  0.63132095  2.0908873 ]
  [-0.26476097 -1.3237371  -0.96894777]
  [-0.26476097  1.1200852   0.10199451]
  [ 0.79428387 -0.3462081  -1.2749313 ]
  [ 0.0378232  -0.83497286  0.2549863 ]]

 [[-1.6263905  -0.83497286 -1.2749313 ]
  [-2.2315593  -1.3237371  -0.8159561 ]
  [ 0.79428387  0.14255619 -0.20398903]
  [ 0.34040737  0.14255619  0.7139616 ]
  [ 0.642992   -0.3462081  -0.5099726 ]
  [ 0.642992    0.87570286  1.1729367 ]]]


In [176]:
result.shape

(2, 2)

In [206]:
a = np.array([100,-23,-15])
print(np.mean(a))
print(np.std(a))

print((a - np.mean(a))/np.std(a))

20.666666666666668
56.19213072624631
[ 1.41182284 -0.77709576 -0.63472707]


In [151]:
tf.nn.conv2d?

In [214]:
tf.reset_default_graph()
update_ops = tf.get_collection(tf.GraphKeys.UPDATE_OPS)
with tf.Session() as sess, tf.control_dependencies(update_ops):
    x = tf.constant(np.array([[41, 100],[21,-23]]).astype(np.float32))
    bn_train = tf.contrib.layers.batch_norm(x, is_training=True, name="bn1")
    
    bn = tf.contrib.layers.batch_norm(x, is_training=False, name="bn1")
    
    init = tf.global_variables_initializer()
    sess.run(init)
    
    print(sess.run([bn_train, bn]))

TypeError: batch_norm() got an unexpected keyword argument 'name'